name: universal_downloader_web
description: Universal Downloader Flutter Web application
publish_to: none
version: 1.1.0+3

environment:
  sdk: ^3.10.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  app_core:
    path: ../../packages/app_core
  download_engine:
    path: ../../packages/download_engine
  sqflite_common_ffi_web: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
