import 'package:path/path.dart' as p;

/// Resolves safe download filenames from URL hints and HTTP response headers.
class FileNameResolver {
  const FileNameResolver._();

  static const _mimeExtensions = {
    'video/mp4': '.mp4',
    'video/webm': '.webm',
    'video/quicktime': '.mov',
    'video/x-matroska': '.mkv',
    'video/x-msvideo': '.avi',
    'video/3gpp': '.3gp',
    'audio/mpeg': '.mp3',
    'audio/mp4': '.m4a',
    'audio/webm': '.opus',
    'audio/aac': '.aac',
    'audio/wav': '.wav',
    'audio/ogg': '.ogg',
    'audio/opus': '.opus',
    'audio/flac': '.flac',
    'image/jpeg': '.jpg',
    'image/jpg': '.jpg',
    'image/png': '.png',
    'image/gif': '.gif',
    'image/webp': '.webp',
    'image/svg+xml': '.svg',
    'application/pdf': '.pdf',
    'application/zip': '.zip',
    'application/x-zip-compressed': '.zip',
    'application/vnd.android.package-archive': '.apk',
    'application/json': '.json',
    'text/plain': '.txt',
    'text/csv': '.csv',
    'text/vcard': '.vcf',
    'text/x-vcard': '.vcf',
    'application/msword': '.doc',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
        '.docx',
    'application/vnd.ms-excel': '.xls',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
        '.xlsx',
    'application/vnd.ms-powerpoint': '.ppt',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation':
        '.pptx',
  };

  /// Reserved for non-provider page URLs. Social platforms use [ContentProviderRegistry].
  static String? pageUrlError(Uri uri) => null;

  static String? parseContentDisposition(String? header) {
    if (header == null || header.isEmpty) return null;

    final encoded = RegExp(
      r"filename\*=(?:UTF-8''|utf-8'')([^;\s]+)",
      caseSensitive: false,
    ).firstMatch(header);
    if (encoded != null) {
      return _decodeDispositionValue(encoded.group(1)!);
    }

    final quoted = RegExp(
      r'filename="([^"]+)"',
      caseSensitive: false,
    ).firstMatch(header);
    if (quoted != null) {
      return _decodeDispositionValue(quoted.group(1)!);
    }

    final plain = RegExp(
      r'filename=([^;\s]+)',
      caseSensitive: false,
    ).firstMatch(header);
    if (plain != null) {
      return _decodeDispositionValue(plain.group(1)!);
    }

    return null;
  }

  static String resolve({
    required Uri uri,
    String? preferredName,
    String? contentDisposition,
    String? contentType,
  }) {
    final mime = _baseMime(contentType);
    if (mime == 'text/html') {
      throw ArgumentError(
        'This URL returns a web page, not a downloadable file. '
        'Use a direct link to the file (for example, ending in .mp4, .mp3, or .pdf).',
      );
    }

    var candidate = preferredName?.trim();
    if (candidate != null && candidate.isEmpty) candidate = null;
    if (candidate != null && _isAutoGeneratedName(candidate)) candidate = null;

    final fromDisposition = parseContentDisposition(contentDisposition);
    final fromUrl = _nameFromUrlPath(uri);

    var name = candidate ?? fromDisposition ?? fromUrl;
    if (name == null || name.isEmpty) {
      name = 'download_${DateTime.now().millisecondsSinceEpoch}';
    }
    name = sanitize(name);

    if (candidate != null && p.extension(candidate).isEmpty) {
      if (fromDisposition != null && p.extension(fromDisposition).isNotEmpty) {
        name = sanitize(fromDisposition);
      } else if (fromUrl != null && p.extension(fromUrl).isNotEmpty) {
        name = sanitize(fromUrl);
      }
    }

    return ensureExtension(name, mime);
  }

  static String sanitize(String raw) {
    var cleaned = raw.replaceAll(RegExp(r'[\\/:*?"<>|\x00-\x1f]'), '_').trim();
    cleaned = cleaned.replaceAll(RegExp(r'\s+'), ' ');
    cleaned = p.basename(cleaned);
    if (cleaned.startsWith('.')) cleaned = cleaned.substring(1);
    return cleaned.isEmpty ? 'download' : cleaned;
  }

  static String ensureExtension(String name, String? mimeType) {
    if (p.extension(name).isNotEmpty) return name;
    final ext = extensionFromMime(mimeType) ?? '.bin';
    return '$name$ext';
  }

  /// Swaps the extension to match [mimeType], keeping the base name.
  static String replaceExtension(String name, String? mimeType) {
    final ext = extensionFromMime(mimeType);
    if (ext == null || ext.isEmpty) return name;
    final sanitized = sanitize(name);
    final current = p.extension(sanitized);
    final base = current.isEmpty
        ? sanitized
        : sanitized.substring(0, sanitized.length - current.length);
    if (base.isEmpty) return 'audio$ext';
    return '$base$ext';
  }

  static String? extensionFromMime(String? mimeType) {
    if (mimeType == null || mimeType.isEmpty) return null;
    final base = _baseMime(mimeType);
    if (_mimeExtensions.containsKey(base)) {
      return _mimeExtensions[base];
    }
    if (base.startsWith('video/')) return '.mp4';
    if (base.startsWith('audio/')) return '.mp3';
    if (base.startsWith('image/')) return '.jpg';
    return null;
  }

  static String? _nameFromUrlPath(Uri uri) {
    final segment = uri.pathSegments.isNotEmpty ? uri.pathSegments.last : '';
    if (segment.isEmpty || segment == '/') return null;
    if (segment.contains('.')) return segment;
    return null;
  }

  static String _baseMime(String? contentType) {
    if (contentType == null) return '';
    return contentType.split(';').first.trim().toLowerCase();
  }

  static bool _isAutoGeneratedName(String name) {
    return RegExp(r'^download_\d+$').hasMatch(name);
  }

  static String _decodeDispositionValue(String raw) {
    final trimmed = raw.trim().replaceAll('"', '');
    try {
      return Uri.decodeComponent(trimmed);
    } on Object {
      return trimmed;
    }
  }
}
